### ISSUE TITLE
Well done Microsoft, where should I get refund of Windows OS

### ISSUE THREAD

**Issue by nitinmukesh** [microsoft/TRELLIS#8]
> Prerequisites
>   Linux is recommended for running the code. The code is not tested on other platforms.

Well done. And we stupid Windows users are paying money to Microsoft for Windows OS. We should rather switch to Linux.

**Comment by andrew-downey** [comment]
This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.

**Comment by YuDeng** [comment]
> > Prerequisites
> > Linux is recommended for running the code. The code is not tested on other platforms.
> 
> Well done. And we stupid Windows users are paying money to Microsoft for Windows OS. We should rather switch to Linux.

Hi, thanks for your interest in this project. 

This repository was initiated from a research prototype. Some of its dependencies are built only for Linux and is not designed to be compatible with various platforms. Currently, we may not be able to devote much effort to make it compatible with the Windows platform, but we will continue to look for solutions. For now, you can try using the [Hugging Face demo](https://huggingface.co/spaces/JeffreyXiang/TRELLIS) provided in the repo for testing. We apologize for this inconvenience.

**Comment by dr-vij** [comment]
Fantastic work!

**Comment by iiiytn1k** [comment]
Just launched this project natively on Windows (without using WSL) with CUDA 12.4, pytorch 2.5.1 and [flash_attn 2.7.1](https://github.com/bdashore3/flash-attention). It works perfectly without any issues.
With RTX 4090 i got sampling ~10.5 it/s for stage 1 and ~8 it/s for stage 2. VRAM usage ~16 Gb.

**Comment by PsiClone99** [comment]
@iiiytn1k Can U please share us the steps/ or what dependencies u installed?

**Comment by sdbds** [comment]
I spent 2 hours compiling all the libraries needed on Windows and writing the automatic installation code, and tested it on the 4090.
https://github.com/microsoft/TRELLIS/issues/10

**Comment by nitinmukesh** [comment]
> This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.

Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.

**Comment by Cubey42** [comment]
> [@PsiClone99](https://github.com/PsiClone99)
> 
> ```
> git clone --recurse-submodules https://github.com/microsoft/TRELLIS.git
> cd TRELLIS
> conda create -n trellis python=3.10
> conda activate trellis 
> 
> pip install torch==2.5.1 torchvision --index-url=https://download.pytorch.org/whl/cu124
> pip install xformers==0.0.28.post3 --index-url=https://download.pytorch.org/whl/cu124
> pip install pillow imageio imageio-ffmpeg tqdm easydict opencv-python-headless scipy ninja rembg onnxruntime trimesh xatlas pyvista pymeshfix igraph transformers
> pip install git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
> pip install https://github.com/bdashore3/flash-attention/releases/download/v2.7.1.post1/flash_attn-2.7.1.post1+cu124torch2.5.1cxx11abiFALSE-cp310-cp310-win_amd64.whl
> pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html
> 
> git clone https://github.com/NVlabs/nvdiffrast.git ./tmp/extensions/nvdiffrast
> pip install ./tmp/extensions/nvdiffrast
> 
> git clone --recurse-submodules https://github.com/JeffreyXiang/diffoctreerast.git ./tmp/extensions/diffoctreerast
> pip install ./tmp/extensions/diffoctreerast
> 
> git clone https://github.com/autonomousvision/mip-splatting.git ./tmp/extensions/mip-splatting
> pip install ./tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/
> 
> cp -r ./extensions/vox2seq ./tmp/extensions/vox2seq
> pip install ./tmp/extensions/vox2seq
> 
> pip install spconv-cu120
> pip install gradio==4.44.1 gradio_litmodel3d==0.0.1
> 
> set ATTN_BACKEND=flash-attn
> set SPCONV_ALGO=native
> python ./app.py
> ```

other than the cp -r command which I just did manually, but worked, thank you.

**Comment by OneOnlineShow** [comment]
> > This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.
> 
> Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.

I agree here. I don't even want to touch this garbage (I mean Linux), and under the only stable Windows 11 IoT LTSC even these scripts above DO NOT work. Horrible experience.

**Comment by astralmedia** [comment]
> > This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.
> 
> Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.

This sort of entitled rudeness does not belong on an open source repo that someone is giving away for free.

**Comment by OneOnlineShow** [comment]
> > > This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.
> > 
> > 
> > Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.
> 
> This sort of entitled rudeness does not belong on an open source repo that someone is giving away for free.

I agree with this, it was very rude to ask Microsoft to make a patch-fix for Windows, because the poor developer in the amount of 1 piece tried for so long to make it for everyone on Linux for free. 
P.S. open source and free are slightly different concepts, somewhere they can be used together, but not in this case.

**Comment by astralmedia** [comment]
> > > > This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.
> > > 
> > > 
> > > Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.
> > 
> > 
> > This sort of entitled rudeness does not belong on an open source repo that someone is giving away for free.
> 
> I agree with this, it was very rude to ask Microsoft to make a patch-fix for Windows, because the poor developer in the amount of 1 piece tried for so long to make it for everyone on Linux for free. P.S. open source and free are slightly different things, sometimes they can be used together, but not in this case. P.P.S. patch-fix has already been made by 1 developer in 2 days of his free time. What was the problem in making it for the staff of developers of this project.. I have no idea.

Your problems go beyond not knowing how to build wheels on windows

**Comment by OneOnlineShow** [comment]
> > > > > This is a research paper, not consumer software. It's cutting edge and pushing the limits of what we as humanity can achieve. You are not being helpful.
> > > > 
> > > > 
> > > > Doesn't matter if it's a research paper or consumer software. Microsoft supported projects MUST work on Windows and that should be their GOAL.
> > > 
> > > 
> > > This sort of entitled rudeness does not belong on an open source repo that someone is giving away for free.
> > 
> > 
> > I agree with this, it was very rude to ask Microsoft to make a patch-fix for Windows, because the poor developer in the amount of 1 piece tried for so long to make it for everyone on Linux for free. P.S. open source and free are slightly different things, sometimes they can be used together, but not in this case. P.P.S. patch-fix has already been made by 1 developer in 2 days of his free time. What was the problem in making it for the staff of developers of this project.. I have no idea.
> 
> Your problems go beyond not knowing how to build wheels on windows

No Linux no problem :)

**Comment by astralmedia** [comment]
> > Your problems go beyond not knowing how to build wheels on windows
> 
> No linux no problem :)

done blowing up the trellis issues, but if you ask nicely for help instead of being rude and assuming, you will have much better luck getting the help you need. No one wants to help after being insulted.

**Comment by OneOnlineShow** [comment]
> No one wants to help after being insulted.
> Your problems go beyond

I'm fine, fortunately there are still hard workers who can do it quickly and without this "compile everything from scratch in an hour to run it once".

**Comment by nitinmukesh** [comment]
It's funny to see these stupid comments.
The original comment was meant for Microsoft not for developers, read carefully. No disrespect was meant for developers but Microsoft organization. They are using money earned from Windows and they are not supporting their own OS for AI.
This is not the first project which was meant for Linux ( one of them is deepspeed, if I remember correctly).

Before commenting understand the message and meant for whom.

**Comment by MrMxyzptlk** [comment]
> [@PsiClone99](https://github.com/PsiClone99)
> 
> ```
> git clone --recurse-submodules https://github.com/microsoft/TRELLIS.git
> cd TRELLIS
> conda create -n trellis python=3.10
> conda activate trellis 
> 
> pip install torch==2.5.1 torchvision --index-url=https://download.pytorch.org/whl/cu124
> pip install xformers==0.0.28.post3 --index-url=https://download.pytorch.org/whl/cu124
> pip install pillow imageio imageio-ffmpeg tqdm easydict opencv-python-headless scipy ninja rembg onnxruntime trimesh xatlas pyvista pymeshfix igraph transformers
> pip install git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8
> pip install https://github.com/bdashore3/flash-attention/releases/download/v2.7.1.post1/flash_attn-2.7.1.post1+cu124torch2.5.1cxx11abiFALSE-cp310-cp310-win_amd64.whl
> pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html
> 
> git clone https://github.com/NVlabs/nvdiffrast.git ./tmp/extensions/nvdiffrast
> pip install ./tmp/extensions/nvdiffrast
> 
> git clone --recurse-submodules https://github.com/JeffreyXiang/diffoctreerast.git ./tmp/extensions/diffoctreerast
> pip install ./tmp/extensions/diffoctreerast
> 
> git clone https://github.com/autonomousvision/mip-splatting.git ./tmp/extensions/mip-splatting
> pip install ./tmp/extensions/mip-splatting/submodules/diff-gaussian-rasterization/
> 
> xcopy /E /H .\extensions\vox2seq\ .\tmp\extensions\vox2seq\
> pip install ./tmp/extensions/vox2seq
> 
> pip install spconv-cu120
> pip install gradio==4.44.1 gradio_litmodel3d==0.0.1
> 
> set ATTN_BACKEND=flash-attn
> set SPCONV_ALGO=native
> python ./app.py
> ```

This worked perfectly for me as well; thank you.

**Comment by Archviz360** [comment]
i got this error 

ERROR: Could not find a version that satisfies the requirement torch==2.5.1 (from versions: 2.6.0+cu124)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for torch==2.5.1

C:\Users\dacia\Desktop\AI photo\Trellis 3d\TRELLIS>pip install xformers==0.0.28.post3 --index-url=https://download.pytorch.org/whl/cu124
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://download.pytorch.org/whl/cu124
ERROR: Could not find a version that satisfies the requirement xformers==0.0.28.post3 (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for xformers==0.0.28.post3

C:\Users\dacia\Desktop\AI photo\Trellis 3d\TRELLIS>pip install pillow imageio imageio-ffmpeg tqdm easydict opencv-python-headless scipy ninja rembg onnxruntime trimesh xatlas pyvista pymeshfix igraph transformers
Defaulting to user installation because normal site-packages is not writeable
Collecting pillow
  Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting imageio
  Downloading imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
Collecting imageio-ffmpeg
  Using cached imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting tqdm
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting easydict
  Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting scipy
  Downloading scipy-1.15.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting ninja
  Downloading ninja-1.11.1.3-py3-none-win_amd64.whl.metadata (5.3 kB)
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Requires-Python >3.7, <3.11; 2.0.33 Requires-Python >3.7, <3.11; 2.0.34 Requires-Python >3.7, <3.11; 2.0.35 Requires-Python >3.7, <3.11; 2.0.36 Requires-Python >3.7, <3.11; 2.0.37 Requires-Python >3.7, <3.11; 2.0.38 Requires-Python >3.7, <3.11; 2.0.39 Requires-Python >3.7, <3.11; 2.0.40 Requires-Python >3.7, <3.11; 2.0.41 Requires-Python >=3.8, <3.12; 2.0.43 Requires-Python >=3.8, <3.12; 2.0.44 Requires-Python >=3.8, <3.12; 2.0.45 Requires-Python >=3.8, <3.12; 2.0.46 Requires-Python >=3.8, <3.12; 2.0.47 Requires-Python >=3.8, <3.12; 2.0.48 Requires-Python >=3.8, <3.12; 2.0.49 Requires-Python >=3.8, <3.12; 2.0.50 Requires-Python >=3.8, <3.12; 2.0.51 Requires-Python >=3.8, <3.12; 2.0.52 Requires-Python >=3.8, <3.12; 2.0.53 Requires-Python >=3.8, <3.12; 2.0.54 Requires-Python >=3.8, <3.12; 2.0.55 Requires-Python >=3.8, <3.13; 2.0.56 Requires-Python >=3.8, <3.13; 2.0.57 Requires-Python <3.13,>=3.8; 2.0.58 Requires-Python <3.13,>=3.8; 2.0.59 Requires-Python <3.13,>=3.8; 2.0.60 Requires-Python <3.13,>=3.8; 2.0.61 Requires-Python <3.13,>=3.8
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for rembg

**Comment by msohne42** [comment]
Não funcionou pra mim

Python nÒo foi encontrado; executar sem argumentos para instalar do Microsoft Store ou desabilitar este atalho em Configuraþ§es > Aplicativos > Configuraþ§es avanþadas do aplicativo > Aliases de execuþÒo do aplicativo.

**Comment by gyrichjames** [comment]
> Não funcionou pra mim
> 
> Python nÒo foi encontrado; executar sem argumentos para instalar do Microsoft Store ou desabilitar este atalho em Configuraþ§es > Aplicativos > Configuraþ§es avanþadas do aplicativo > Aliases de execuþÒo do aplicativo.

Experimente este, funcionou para mim:

https://github.com/IgorAherne/trellis-stable-projectorz/releases/tag/latest

**Comment by gyrichjames** [comment]
> > python ./app.py
> 
> For me it fails with
> 
> ```
>   File "C:\Users\gleb\miniconda3\envs\trellis\lib\site-packages\flash_attn\ops\triton\rotary.py", line 7, in <module>
>     import triton
> ModuleNotFoundError: No module named 'triton'
> ```

I was able to get it working by using the simple installer created by the guy who makes StableProjectorz, an awesome 3d model texturing app that uses AI to generate textures that you can modify on the model (https://stableprojectorz.com/)(It's free).

Anyway, he released a Trellis installer that worked for me, see his reddit post: 

https://www.reddit.com/r/StableDiffusion/comments/1hkiapy/trellis_3d_generation_windows_oneclick_installer/

Hope it helps.
